### PR TITLE
MFTAnaSim library evolution

### PR DESCRIPTION
**Pull request by bovulpes**

### CODE REVIEW

**Comment by rpezzi** [comment]
Hi Bogdan, thanks for moving this forward. Can you please provide a an example of use? Perhaps detailed steps of the workflow on the Readme?

**Comment by bovulpes** [comment]
Hi Rafael, 

I had a presentation prepared for today, maybe next time. 
It is attached to this message. 

cheers, 

Bogdan. 


De: "rpezzi" ***@***.***> 
À: "rpezzi/O2Simulations" ***@***.***> 
Cc: "Bogdan Vulpescu" ***@***.***>, "Author" ***@***.***> 
Envoyé: Mardi 6 Juillet 2021 17:48:49 
Objet: Re: [rpezzi/O2Simulations] MFTAnaSim library evolution (#4) 





Hi Bogdan, thanks for moving this forward. Can you please provide a an example of use? Perhaps detailed steps of the workflow on the Readme?

**Comment by bovulpes** [comment]
Hi Rafael, 

I had a presentation prepared for today, maybe next time. 
It is attached to this message. 

cheers, 

Bogdan. 



De: "rpezzi" ***@***.***> 
À: "rpezzi/O2Simulations" ***@***.***> 
Cc: "Bogdan Vulpescu" ***@***.***>, "Author" ***@***.***> 
Envoyé: Mardi 6 Juillet 2021 17:48:49 
Objet: Re: [rpezzi/O2Simulations] MFTAnaSim library evolution (#4) 





Hi Bogdan, thanks for moving this forward. Can you please provide a an example of use? Perhaps detailed steps of the workflow on the Readme?

**Comment by bovulpes** [comment]
Hi @rpezzi 
This PR ends up with the deletion of the "lib" directory in this repository, since everything is transferred to MFTana.
I have added there your changes on the existing files, but not the new task boilerplate files.
Can you add them there, please and let "die" this part of O2Simulations, as we have agreed ?

**Comment by rpezzi** [comment]
Thanks Bogdan. I will open a PR on the new repo.

**Pull request merged**
